ComputerStore/Components/CartSummaryViewComponent.cs
using ComputerStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;

namespace ComputerStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CartSummaryViewComponent(Cart cart)
        {
            _cart = cart ?? throw new ArgumentNullException(nameof(cart));
        }

        public IViewComponentResult Invoke() => View(_cart);
    }
}

ComputerStore/Controllers/CartController.cs
using ComputerStore.Infrastructure;
using ComputerStore.Models;
using ComputerStore.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace ComputerStore.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductRepository _repository;
        private readonly Cart _cart;

        public CartController(IProductRepository repository, Cart cart)
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _cart = cart ?? throw new ArgumentNullException(nameof(cart));
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = _cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            var product = _repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                _cart.AddItem(product, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            var product = _repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                _cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

ComputerStore/Views/Shared/ProductSummary.cshtml
@model Product

<div class="card border-primary m-1">
    <div class="card-header pt-3">
        @Model.Name
        <h5 class="badge badge-pill badge-primary float-right">@Model.Price.ToString("c")</h5>
    </div>
    <form id="@Model.ProductId" asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductId" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <div class="card-body">
            <div class="card-text p-1">@Model.Description</div>
            <button type="submit"
                    class="btn btn-success btn-sm float-right mb-3">
                Add to cart
            </button>
        </div>
    </form>    
</div>

ComputerStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="/lib/bootstrap/**/*.min.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error { border-color: red; background-color: #fee }
    </style>
    <script src="/lib/jquery/jquery.min.js"></script>
    <script src="/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <div class="navbar navbar-dark bg-primary" role="navigation">
        <a class="col navbar-brand" href="#">Admin panel - @ViewBag.Title</a>
        <div class="col-2">
            <a class="btn btn-sm btn-primary"
               asp-action="Logout" asp-controller="Account">Log Out</a>
        </div>
    </div>
    @if (TempData["message"] != null)
    {
        <div class="m-1 alert alert-success">@TempData["message"]</div>
    }
    <div class="m-1">
        @RenderBody()
    </div>
</body>
</html>

ComputerStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="/lib/bootstrap/**/*.min.css"/>
    <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/*.css"/>
    <title>Computer Store</title>
</head>
<body>
    <div class="navbar navbar-dark bg-primary justify-content-between" role="navigation">
        <a class="col-1 navbar-brand" href="#">COMPUTER STORE</a>
        <div class="col-4 text-right">
            @await Component.InvokeAsync("CartSummary")
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>